# Generated by Django 4.1.4 on 2024-02-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='last_name',
        ),
    ]
